application: upheld-quasar-641
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /static
  static_dir: static

# main app should below other urls
- url: /.*
  script: main.app

libraries:
- name: django
  version: "latest"
